# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.sepolia]
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_7/demo"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "deployer"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true

[sncast.devnet]
url = "http://localhost:5050"
account = "devnet-deployer"
